apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - github.com/kubeflow/manifests/katib/katib-crds/base?ref=v1.2-branch
  - github.com/kubeflow/manifests/katib/katib-controller/base?ref=v1.2-branch
patchesStrategicMerge:
  - katib-db-manager-deployment.yaml
secretGenerator:
  - name: katib-mysql-secrets
    behavior: merge
    envs:
      - secrets.env
commonLabels:
  app.kubernetes.io/component: katib
  app.kubernetes.io/name: katib-controller